using System;
using System.Collections.Generic;

#nullable disable

namespace projectMigration.Models
{
    public partial class FinsClientmaster
    {
        public string CliBankcode { get; set; }
        public string CliCustId { get; set; }
        public string CliTitle { get; set; }
        public string CliFirstName { get; set; }
        public string CliMiddleName { get; set; }
        public string CliLastName { get; set; }
        public DateTime? CliDob { get; set; }
        public string CliGender { get; set; }
        public string CliPanNo { get; set; }
        public string CliUid { get; set; }
        public string CliBranchId { get; set; }
        public string CliResAddr1 { get; set; }
        public string CliResAddr2 { get; set; }
        public string CliResAddr3 { get; set; }
        public string CliResArea { get; set; }
        public string CliResLandmark { get; set; }
        public int? CliResPincode { get; set; }
        public int? CliResCityId { get; set; }
        public int? CliResStateId { get; set; }
        public DateTime? CliResAddrChgDate { get; set; }
        public string CliResPhone { get; set; }
        public string CliResStd { get; set; }
        public string CliResMobile { get; set; }
        public DateTime? CliResMobileChgDate { get; set; }
        public string CliResEmail { get; set; }
        public DateTime? CliResEmailDate { get; set; }
        public string CliOfcAddr1 { get; set; }
        public string CliOfcAddr2 { get; set; }
        public string CliOfcAddr3 { get; set; }
        public string CliOfcArea { get; set; }
        public string CliOfcLandmark { get; set; }
        public int? CliOfcPincode { get; set; }
        public int? CliOfcCityId { get; set; }
        public int? CliOfcStateId { get; set; }
        public DateTime? CliOfcAddrDate { get; set; }
        public string CliOfcPhone { get; set; }
        public string CliOfcStd { get; set; }
        public string CliOfcMobile { get; set; }
        public DateTime? CliOfcMobileChgDate { get; set; }
        public string CliOfcEmail { get; set; }
        public DateTime? CliOfcEmailDate { get; set; }
        public string CliMailingAddr { get; set; }
        public long? CliCreditLimit { get; set; }
        public long? CliTotalAuthBlocked { get; set; }
        public long? CliTotalLoanBlocked { get; set; }
        public string CliEcsBankName { get; set; }
        public string CliEcsBankBranchName { get; set; }
        public string CliEcsMicrCode { get; set; }
        public string CliEcsIfscCode { get; set; }
        public string CliEcsAccountNo { get; set; }
        public long? CliEcsLimit { get; set; }
        public long? CliEcsAuthBlocked { get; set; }
        public long? CliEcsLoanBlocked { get; set; }
        public long? CliEcsAvailableLimit { get; set; }
        public DateTime? CliEcsExpiryDate { get; set; }
        public DateTime? CliEcsUpdateDate { get; set; }
        public string CliCibilScore { get; set; }
        public DateTime? CliCibilScoreDate { get; set; }
        public DateTime? CliCtrChargedDate { get; set; }
        public string CliDndSms { get; set; }
        public string CliDndEmail { get; set; }
        public string CliDocsPendingFlag { get; set; }
        public DateTime? CliDocsDate { get; set; }
        public bool? CliVehicleType { get; set; }
        public string CliVehicleRegistration { get; set; }
        public DateTime? CliBaseLoanFdd { get; set; }
        public string CliDedupeFromId { get; set; }
        public decimal? CliDedupeToId { get; set; }
        public DateTime? CliDedupeDate { get; set; }
        public string CliType { get; set; }
        public string CliSystemBlockCode { get; set; }
        public DateTime? CliSystemBlockDate { get; set; }
        public DateTime? CliSystemUnblockDate { get; set; }
        public string CliManualBlockCode { get; set; }
        public DateTime? CliManualBlockDate { get; set; }
        public DateTime? CliManualUnblockDate { get; set; }
        public string CliBscore { get; set; }
        public string CliOldResMobile { get; set; }
        public string CliOldOfcMobile { get; set; }
        public DateTime? CliCreationDate { get; set; }
        public string CliFraudProneFlag { get; set; }
        public string CliEcsUpdateMode { get; set; }
        public string CliSmtFlag { get; set; }
        public DateTime? CliLastModifyDtWl { get; set; }
        public DateTime? CliLastModifyDtBfl { get; set; }
        public string CliDocsFlagRrn { get; set; }
        public string CliInstaRrn { get; set; }
        public string CliSystemUnblockReason { get; set; }
        public string CliManualUnblockReason { get; set; }
        public DateTime? CliLastLoanDate { get; set; }
        public DateTime? CliLastAuthDate { get; set; }
        public string CliBaseLoanNumber { get; set; }
        public string CliCibilScoreSource { get; set; }
        public decimal? CliNoOfLinkedCust { get; set; }
        public string CliBlockClassification { get; set; }
        public DateTime? CliBlockClassModifyDt { get; set; }
        public string CliStatus { get; set; }
        public DateTime? CliIvrUpd { get; set; }
        public DateTime? CliStartDate { get; set; }
        public DateTime? CliEndDate { get; set; }
        public string CliTxnScore { get; set; }
        public string CliEcsRegNo { get; set; }
        public int? CliCreditRewardsPts { get; set; }
        public string CliCredcrdOfrType { get; set; }
        public string CliCredcrdOfrBflccid { get; set; }
        public long? CliCredcrdOfrLim { get; set; }
        public string CliCredcrdPancopyExist { get; set; }
        public long? CliCredcrdOtbl { get; set; }
        public DateTime? CliAnnualFeeDueDt { get; set; }
        public string CliMoratPaymentFlag { get; set; }
        public int? CliCibilv3Score { get; set; }
        public string CliCredcrdKycFlag { get; set; }
        public short? CliCredcrdSplOffer { get; set; }
        public string CliPanStatus { get; set; }
        public string CliImpsFirstHolderName { get; set; }
        public string CliImpsSecondHolderName { get; set; }
        public string CliReKycFlag { get; set; }
        public string CliCcNccFlag { get; set; }
        public string CliSdkSegment { get; set; }
        public DateTime? CliSdkSegmentDate { get; set; }
        public short? CliNoOfActiveLoans { get; set; }
    }
}
