using System;
using System.Collections.Generic;

#nullable disable

namespace projectMigration.Models
{
    public partial class FinsProfilemaster
    {
        public string Profilestatus { get; set; }
        public int ProfileId { get; set; }
        public string ProfileIdIdentifier { get; set; }
        public string ProfileOwner { get; set; }
        public decimal? Dealerid { get; set; }
        public string Txntype { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Dob { get; set; }
        public string Gender { get; set; }
        public string PanNo { get; set; }
        public string UidNo { get; set; }
        public string CustomerBranchId { get; set; }
        public string ResidenceAddress1 { get; set; }
        public string ResidenceAddress2 { get; set; }
        public string ResidenceAddress3 { get; set; }
        public string ResidenceArea { get; set; }
        public string ResidenceLandmark { get; set; }
        public string ResidencePincode { get; set; }
        public string ResidenceCityId { get; set; }
        public string ResidenceStateId { get; set; }
        public string ResidenceAddressChangeDate { get; set; }
        public string ResidencePhone { get; set; }
        public string ResidenceStd { get; set; }
        public string ResidenceMobile { get; set; }
        public string ResidenceMobileChangeDate { get; set; }
        public string ResidenceEmail { get; set; }
        public string LbcliResidenceEmailDate { get; set; }
        public string MailingAddress { get; set; }
        public string CustomerCreditLimit { get; set; }
        public string CustomerTotalAuthBlocked { get; set; }
        public string CustomerTotalLoanBlocked { get; set; }
        public string CustomerEcsBankName { get; set; }
        public string CustomerEcsBankBranchName { get; set; }
        public string CustomerEcsMicrCode { get; set; }
        public string CustomerEcsIfscCode { get; set; }
        public string CustomerEcsAccountNo { get; set; }
        public string CustomerEcsLimit { get; set; }
        public string CustomerEcsAuthBlocked { get; set; }
        public string CustomerEcsLoanBlocked { get; set; }
        public string CustomerEcsAvailableLimit { get; set; }
        public string CustomerEcsExpiryDate { get; set; }
        public string CliEcsUpdateMode { get; set; }
        public string EcsUpdateDate { get; set; }
        public string CustomerCibilScore { get; set; }
        public string CustomerCibilScoreDate { get; set; }
        public string CustomerCtrChargedDate { get; set; }
        public string CustomerDndSms { get; set; }
        public string CustomerDndEmail { get; set; }
        public string CustomerDocsPendingFlag { get; set; }
        public string CustomerDocsDate { get; set; }
        public string CustomerVehicleType { get; set; }
        public string CustomerVehicleRegistration { get; set; }
        public string BaseLoanFdd { get; set; }
        public string DedupeFromCustomerId { get; set; }
        public string DedupeToCustomerId { get; set; }
        public string DedupeDate { get; set; }
        public string CustomerType { get; set; }
        public string CustomerSystemBlockCode { get; set; }
        public string CustomerSystemBlockReason { get; set; }
        public string CustomerSystemBlockDate { get; set; }
        public string CustomerSystemUnblockDate { get; set; }
        public string CustomerManualBlockCode { get; set; }
        public string CustomerManualUnblockReason { get; set; }
        public string CustomerManualBlockDate { get; set; }
        public string CustomerManualUnblockDate { get; set; }
        public string LbcliOldResidenceMobile { get; set; }
        public string CustomerCreationDate { get; set; }
        public string CustomerStatus { get; set; }
        public string CliFraudProneFlag { get; set; }
        public string CliSmtFlag { get; set; }
        public string CliLastModifyDtWl { get; set; }
        public string CliLastModifyDtBfl { get; set; }
        public string CliDocsFlagRrn { get; set; }
        public string CliInstaRrn { get; set; }
        public string LastAuthDate { get; set; }
        public string LastLoanDate { get; set; }
        public string Bscore { get; set; }
        public string AccountId { get; set; }
        public string CustomerId { get; set; }
        public string AccountType { get; set; }
        public string AccountCreditLimit { get; set; }
        public string AccountTotalAuthBlocked { get; set; }
        public string AccountTotalLoanBlocked { get; set; }
        public string AccountAdjLimit { get; set; }
        public string AccountAdjLimitAdjDate { get; set; }
        public string AccountTempLimit { get; set; }
        public string AccountTempLimitStartDt { get; set; }
        public string AccountTempLimitEndDt { get; set; }
        public string AccountSystemBlockCode { get; set; }
        public string AccountSystemBlockDate { get; set; }
        public string AccountSystemUnblockDate { get; set; }
        public string AccountSystemUnblockReason { get; set; }
        public string AccountManualBlockCode { get; set; }
        public string AccountManualBlockDate { get; set; }
        public string AccountManualUnblockDate { get; set; }
        public string AccountManualUnblockReason { get; set; }
        public string AccountVipNonvipFlag { get; set; }
        public string AccountLastAuthDate { get; set; }
        public string ProcessDeviationFlag { get; set; }
        public string ProcessDeviationEndDate { get; set; }
        public string AccountCreationDate { get; set; }
        public string LbcliOldestActPriCard { get; set; }
        public string NameOfChmpChllg { get; set; }
        public string AccNoOfAddonCards { get; set; }
        public string AccTotalNoOfCards { get; set; }
        public string AccLastModifyDtWl { get; set; }
        public string AccLastModifyDtBfl { get; set; }
        public string AccBlockClassification { get; set; }
        public string AccBlockClassModifyDt { get; set; }
        public string AccBestLimit { get; set; }
        public string CardCardNo { get; set; }
        public string CardCustId { get; set; }
        public string CardAccountId { get; set; }
        public string CardCardType { get; set; }
        public string CardCardCreaDt { get; set; }
        public string CardExpDt { get; set; }
        public string CardDealerCd { get; set; }
        public string CardGrpDealerCd { get; set; }
        public string CardGrpDealerName { get; set; }
        public string CardSrcType { get; set; }
        public string CardPrimaryAddOnInd { get; set; }
        public string CardPin { get; set; }
        public string CardEmiCardCharges { get; set; }
        public string CardActivationDt { get; set; }
        public string CardLatestCardStatus { get; set; }
        public string CardReissueDt { get; set; }
        public string CardReplNewCard { get; set; }
        public string CardReplOldCard { get; set; }
        public string CardWecareRefNo { get; set; }
        public string CardLastAuthDt { get; set; }
        public string CardLastModifyDt { get; set; }
        public string CardUserName { get; set; }
        public string CardWrngPinAttmpt { get; set; }
        public string CardNameOnCard { get; set; }
        public string LaddonMobile { get; set; }
        public string LaddonResidenceEmail { get; set; }
        public string LaddonRelationshipPrim { get; set; }
        public string LaddonDob { get; set; }
        public string LaddonDocsFlag { get; set; }
        public string LaddonLastModifyDt { get; set; }
        public string LaddonMobChangeDt { get; set; }
        public string LaddonOldMobilNo { get; set; }
        public string CardDesign { get; set; }
        public string CardTypeIdentifier { get; set; }
        public string CardSourceInd { get; set; }
        public string CardSystemBlockCode { get; set; }
        public string CardSystemUnblockReason { get; set; }
        public string CardSystemBlockDate { get; set; }
        public string CrdSystemUnblockDate { get; set; }
        public string CrdManualBlockCode { get; set; }
        public string CrdManualBlockDate { get; set; }
        public string CrdManualUnblockDate { get; set; }
        public string CrdChargedRrn { get; set; }
        public string CrdWrngOtpAttmpt { get; set; }
        public string CrdLastModifyDtWl { get; set; }
        public string CrdLastModifyDtBfl { get; set; }
        public string CrdFundedNonfunded { get; set; }
        public string CrdManualUnblockReason { get; set; }
        public string DigitalColour { get; set; }
        public string NonDigitalColour { get; set; }
        public string ActivityMode { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Authcode { get; set; }
        public string OldOfcMobile { get; set; }
        public string SystemUnblockReason { get; set; }
        public string BaseLoanNumber { get; set; }
        public string CibilScoreSource { get; set; }
        public string NoOfLinkedCust { get; set; }
        public string BlockClassification { get; set; }
        public string BlockClassModifyDt { get; set; }
        public string CliStartDate { get; set; }
        public string CliEndDate { get; set; }
        public string TxnScore { get; set; }
        public string EcsRegNo { get; set; }
        public string CreditRewardsPts { get; set; }
        public string CredcrdOfrType { get; set; }
        public string CredcrdOfrBflccid { get; set; }
        public string CredcrdOfrLim { get; set; }
        public string CredcrdPancopyExist { get; set; }
        public string CredcrdOtbl { get; set; }
        public string AnnualFeeDueDt { get; set; }
        public string AccStartDate { get; set; }
        public string AccEndDate { get; set; }
        public string CliMoratPaymentFlag { get; set; }
        public string CliSdkSegment { get; set; }
        public string Userid { get; set; }
        public string Useremail { get; set; }
        public string UnblockBlockCode { get; set; }
    }
}
