using System;
using System.Collections.Generic;

#nullable disable

namespace projectMigration.Models
{
    public partial class FinsAuthorizationmaster
    {
        public string AuthRrnumber { get; set; }
        public string AuthCardNum { get; set; }
        public string AuthAccountId { get; set; }
        public string AuthCustomerId { get; set; }
        public string AuthBankCode { get; set; }
        public string AuthMerchantBranchId { get; set; }
        public string AuthMobile { get; set; }
        public string AuthAuthCode { get; set; }
        public string AuthMid { get; set; }
        public string AuthTid { get; set; }
        public string AuthMerchantName { get; set; }
        public string AuthCardExp { get; set; }
        public DateTime? AuthReqDate { get; set; }
        public string AuthAuthAmt { get; set; }
        public string AuthMatchFlag { get; set; }
        public string AuthResponseCode { get; set; }
        public string AuthSourceReverse { get; set; }
        public string AuthProcessCode { get; set; }
        public string AuthPosEntryMode { get; set; }
        public string AuthTraceAuditNumber { get; set; }
        public string AuthPartnerEdcChannel { get; set; }
        public string AuthOriginalRrnumber { get; set; }
        public string AuthProductId { get; set; }
        public string AuthSchemeCode { get; set; }
        public string AuthManufacturerId { get; set; }
        public string AuthAssetCode { get; set; }
        public string AuthModelId { get; set; }
        public string AuthTenor { get; set; }
        public string AuthEmiAmt { get; set; }
        public string AuthAdvanceEmiAmt { get; set; }
        public string AuthImei { get; set; }
        public string AuthParentRrnumber { get; set; }
        public string AuthCustomerDueCycle { get; set; }
        public string AuthChargeId1 { get; set; }
        public string AuthChargeId1Amt { get; set; }
        public string AuthChargeId2 { get; set; }
        public string AuthChargeId2Amt { get; set; }
        public string AuthChargeId3 { get; set; }
        public string AuthChargeId3Amt { get; set; }
        public string AuthChargeId4 { get; set; }
        public string AuthChargeId4Amt { get; set; }
        public string AuthChargeId5 { get; set; }
        public string AuthChargeId5Amt { get; set; }
        public string AuthCreditProgramCode { get; set; }
        public string AuthLastUpdDate { get; set; }
        public string AuthUserName { get; set; }
        public string AuthFraudFlag { get; set; }
        public string AuthAddrChngFlg { get; set; }
        public string AuthRelationshipType { get; set; }
        public string AuthNoOfAdvEmi { get; set; }
        public string AuthProcessingFee { get; set; }
        public string AuthCibilDone { get; set; }
        public string AuthCibilDate { get; set; }
        public string AuthCibilTime { get; set; }
        public string AuthCibilScore { get; set; }
        public string AuthDbdSubvenPerc { get; set; }
        public string AuthMeDealerId { get; set; }
        public string AuthCardCharges { get; set; }
        public string AuthIpAddress { get; set; }
        public string AuthInterestRate { get; set; }
        public string AuthAvailableLimit { get; set; }
        public string AuthExceptionMsg { get; set; }
        public string AuthPromoCode { get; set; }
        public string AuthOrgTxnAmt { get; set; }
        public string AuthVasAmt { get; set; }
        public string AuthMobileTransaction { get; set; }
        public string AuthFailedRuleId { get; set; }
        public string AuthOldCibilScore { get; set; }
        public string AuthOldCibilDate { get; set; }
        public string AuthOldCibilTime { get; set; }
        public string AuthTxnMobileNo { get; set; }
        public string AuthDfsFlag { get; set; }
        public string AuthDfsPremiumAmount { get; set; }
        public string AuthDfsAcquringChannel { get; set; }
        public string AuthDfsEFlag { get; set; }
        public string AuthBatchId { get; set; }
        public string AuthOtpRequestId { get; set; }
        public string AuthOtpId { get; set; }
        public string AuthCustomerName { get; set; }
        public string AuthField63Tag96 { get; set; }
        public string AuthEcsAvailableLimit { get; set; }
        public string AuthDowNumberPayment { get; set; }
        public DateTime? AuthFirstDueDate { get; set; }
        public string AuthEcsBankName { get; set; }
        public string AuthEcsAccountNumber { get; set; }
        public string AuthMicrCode { get; set; }
        public string AuthAddressLine1 { get; set; }
        public string AuthAddressLine2 { get; set; }
        public string AuthAddressLine3 { get; set; }
        public string AuthResidenceCity { get; set; }
        public string AuthFirstTranscatioNo { get; set; }
        public string AuthOtpVerificReslt { get; set; }
        public string AuthTransactionBranchId { get; set; }
        public string AuthDeliveryPinCode { get; set; }
        public string AuthMbd { get; set; }
        public string AuthFirstSwipeFlag { get; set; }
        public string AuthEcsMandateRequired { get; set; }
        public string AuthAddOnFirstTran { get; set; }
        public string AuthChallengerEligibleFlag { get; set; }
        public string AuthChallengerRuleId1 { get; set; }
        public string AuthAccountLimitUtil { get; set; }
        public string AuthTliUtilizedFlg { get; set; }
        public string AuthPosReinventAuthcode { get; set; }
        public string AuthDocumentRequiredFlg { get; set; }
        public string AuthOrderNo { get; set; }
        public string AuthCdParentRrn { get; set; }
        public string AuthFosMobile { get; set; }
        public string AuthMobileChangedFlag { get; set; }
        public string AuthPinumberEntered { get; set; }
        public string AuthPosReinventInvoiceAmt { get; set; }
        public string AuthPartialCnclId { get; set; }
        public string AuthCtrFlag { get; set; }
        public string AuthResponseDesc { get; set; }
        public string AuthPartialCnclChrgs { get; set; }
        public string AuthPartialDbdRefund { get; set; }
        public string AuthPartialCnclFlag { get; set; }
        public string AuthSettledFlag { get; set; }
        public string AuthPrimaryAddOnInd { get; set; }
        public decimal? AuthNoOfAddonCards { get; set; }
        public string AuthTxnSource { get; set; }
        public string AuthFinancingTypeCode { get; set; }
        public string AuthProductCodeType { get; set; }
        public string AuthAvlAmtBeforeTxn { get; set; }
        public string AuthAvlAmtAfterTxn { get; set; }
        public string AuthLoanToValue { get; set; }
        public string AuthAcqChannelId { get; set; }
        public string AuthIdentifier { get; set; }
        public decimal? SeqId { get; set; }
        public string AuthExtraPricingLimit { get; set; }
        public string AuthAccCardLimit { get; set; }
        public string AuthCardType { get; set; }
        public string AuthCardDesign { get; set; }
        public string AuthCoBrandLimitFlag { get; set; }
        public string AuthCoBrandCardCode { get; set; }
        public string AuthStoreId { get; set; }
        public string AuthModelMake { get; set; }
        public string AuthBreStip { get; set; }
        public string AuthUniqueCancellationId { get; set; }
        public string AuthCancelAmtAdjstFrom { get; set; }
        public DateTime? AuthDateLtxnMatch { get; set; }
        public string AuthCardtypeIdentifier { get; set; }
        public string AuthEcslmtamt { get; set; }
        public string AuthRequestid { get; set; }
        public string AuthProdDesc { get; set; }
        public decimal AuthSeqNo { get; set; }
        public DateTime? AuthSettledFlagDate { get; set; }
        public string AuthSfdcorg { get; set; }
        public string AuthFraudTxnFlag { get; set; }
        public DateTime? AuthFraudTxnDate { get; set; }
        public string AuthSdkSegment { get; set; }
        public DateTime? AuthSdkSegmentDate { get; set; }
        public string AuthDigitalTxnEligibility { get; set; }
        public string AuthNonDigitalTxnEligibility { get; set; }
        public DateTime? AuthPartnerapiRequestdate { get; set; }
        public DateTime? AuthReqdatetime { get; set; }
        public DateTime? AuthOtpgentime { get; set; }
        public string DeliveryAddress { get; set; }
    }
}
